#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

mkdir -p "${WORKLOAD_DIR}"

index_file="${WORKLOAD_DIR}/workload_index.tsv"
printf 'size_mb\trecordcount\tfieldcount\tfieldlength\tapprox_value_bytes_per_record\tworkload_file\n' > "${index_file}"

fieldcount="${FIELD_COUNT:-${DEFAULT_FIELD_COUNT}}"
fieldlength="${FIELD_LENGTH:-${DEFAULT_FIELD_LENGTH}}"
record_value_bytes="$(record_value_bytes_per_record)"
operationcount="${OPERATION_COUNT:-${DEFAULT_OPERATION_COUNT}}"

while IFS= read -r size_mb; do
  [[ -n "${size_mb}" ]] || continue

  recordcount="$(recordcount_for_size_mb "${size_mb}")"
  workload_file="$(workload_file_for_size_mb "${size_mb}")"

  {
    printf '# Auto-generated by %s\n' "${BASH_SOURCE[0]}"
    printf '# Requested logical working set: %s MiB\n' "${size_mb}"
    printf '# recordcount=%s, fieldcount=%s, fieldlength=%s\n' "${recordcount}" "${fieldcount}" "${fieldlength}"
    printf '# Approximate serialized value bytes per record: %s\n' "${record_value_bytes}"
    printf 'recordcount=%s\n' "${recordcount}"
    printf 'operationcount=%s\n' "${operationcount}"
    printf 'workload=site.ycsb.workloads.CoreWorkload\n'
    printf '\n'
    printf 'fieldcount=%s\n' "${fieldcount}"
    printf 'fieldlength=%s\n' "${fieldlength}"
    printf 'fieldlengthdistribution=constant\n'
    printf 'fieldnameprefix=f\n'
    printf 'readallfields=true\n'
    printf '\n'
    printf 'readproportion=1\n'
    printf 'updateproportion=0\n'
    printf 'scanproportion=0\n'
    printf 'insertproportion=0\n'
    printf 'readmodifywriteproportion=0\n'
    printf '\n'
    printf 'requestdistribution=uniform\n'
    printf 'insertorder=hashed\n'
  } > "${workload_file}"

  printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
    "${size_mb}" \
    "${recordcount}" \
    "${fieldcount}" \
    "${fieldlength}" \
    "${record_value_bytes}" \
    "${workload_file}" >> "${index_file}"
done < <(list_sizes)

log "Generated workloads in ${WORKLOAD_DIR}"
